config/routes.rb
EndApp::Application.routes.draw do
  resources :docents

  resources :labos

  resources :students

  resources :users
  
  resources :lijst
  

end

app/models/docent.rb
class Docent < ActiveRecord::Base
end

app/models/labo.rb
class Labo < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, :last_name, :email, :presence => true
	validates :email, :uniqueness => true
	validates :password, :presence => true, :length => { :within => 6..12 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/docents_controller.rb
class DocentsController < ApplicationController
  # GET /docents
  # GET /docents.xml
  def index
    @docents = Docent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @docents }
    end
  end

  # GET /docents/1
  # GET /docents/1.xml
  def show
    @docent = Docent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @docent }
    end
  end

  # GET /docents/new
  # GET /docents/new.xml
  def new
    @docent = Docent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @docent }
    end
  end

  # GET /docents/1/edit
  def edit
    @docent = Docent.find(params[:id])
  end

  # POST /docents
  # POST /docents.xml
  def create
    @docent = Docent.new(params[:docent])

    respond_to do |format|
      if @docent.save
        format.html { redirect_to(@docent, :notice => 'Docent was successfully created.') }
        format.xml  { render :xml => @docent, :status => :created, :location => @docent }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @docent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /docents/1
  # PUT /docents/1.xml
  def update
    @docent = Docent.find(params[:id])

    respond_to do |format|
      if @docent.update_attributes(params[:docent])
        format.html { redirect_to(@docent, :notice => 'Docent was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @docent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /docents/1
  # DELETE /docents/1.xml
  def destroy
    @docent = Docent.find(params[:id])
    @docent.destroy

    respond_to do |format|
      format.html { redirect_to(docents_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/labos_controller.rb
class LabosController < ApplicationController
  # GET /labos
  # GET /labos.xml
  def index
    @labos = Labo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @labos }
    end
  end

  # GET /labos/1
  # GET /labos/1.xml
  def show
    @labo = Labo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @labo }
    end
  end

  # GET /labos/new
  # GET /labos/new.xml
  def new
    @labo = Labo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @labo }
    end
  end

  # GET /labos/1/edit
  def edit
    @labo = Labo.find(params[:id])
  end

  # POST /labos
  # POST /labos.xml
  def create
    @labo = Labo.new(params[:labo])

    respond_to do |format|
      if @labo.save
        format.html { redirect_to(@labo, :notice => 'Labo was successfully created.') }
        format.xml  { render :xml => @labo, :status => :created, :location => @labo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @labo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /labos/1
  # PUT /labos/1.xml
  def update
    @labo = Labo.find(params[:id])

    respond_to do |format|
      if @labo.update_attributes(params[:labo])
        format.html { redirect_to(@labo, :notice => 'Labo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @labo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /labos/1
  # DELETE /labos/1.xml
  def destroy
    @labo = Labo.find(params[:id])
    @labo.destroy

    respond_to do |format|
      format.html { redirect_to(labos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/lijst_controller.rb
class LijstController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.xml
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @students }
    end
  end

  # GET /students/1
  # GET /students/1.xml
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/new
  # GET /students/new.xml
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.xml
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to(@student, :notice => 'Student was successfully created.') }
        format.xml  { render :xml => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.xml
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(@student, :notice => 'Student was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.xml
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to(students_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docents_helper.rb
module DocentsHelper
end

app/helpers/labos_helper.rb
module LabosHelper
end

app/helpers/lijst_helper.rb
module LijstHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/docents/_form.html.erb
<%= form_for(@docent) do |f| %>
  <% if @docent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@docent.errors.count, "error") %> prohibited this docent from being saved:</h2>

      <ul>
      <% @docent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docents/edit.html.erb
<h1>Editing docent</h1>

<%= render 'form' %>

<%= link_to 'Show', @docent %> |
<%= link_to 'Back', docents_path %>

app/views/docents/index.html.erb
<h1>Docenten</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @docents.each do |docent| %>
  <tr>
    <td><%= docent.first_name %></td>
    <td><%= docent.last_name %></td>
    <td><%= docent.email %></td>
    <td><%= docent.password %></td>
    <td><%= link_to 'Show', docent %></td>
    <td><%= link_to 'Edit', edit_docent_path(docent) %></td>
    <td><%= link_to 'Destroy', docent, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Docent', new_docent_path %>
<a href="http://localhost:3000/">Terug</a>

app/views/docents/new.html.erb
<h1>New docent</h1>

<%= render 'form' %>

<%= link_to 'Back', docents_path %>

app/views/docents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @docent.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @docent.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @docent.email %>
</p>

<p>
  <b>Password:</b>
  <%= @docent.password %>
</p>


<%= link_to 'Edit', edit_docent_path(@docent) %> |
<%= link_to 'Back', docents_path %>

app/views/labos/_form.html.erb
<%= form_for(@labo) do |f| %>
  <% if @labo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@labo.errors.count, "error") %> prohibited this labo from being saved:</h2>

      <ul>
      <% @labo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :labo_naam %><br />
    <%= f.text_field :labo_naam %>
  </div>
  <div class="field">
    <%= f.label :studiepunten %><br />
    <%= f.text_field :studiepunten %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labos/edit.html.erb
<h1>Editing labo</h1>

<%= render 'form' %>

<%= link_to 'Show', @labo %> |
<%= link_to 'Back', labos_path %>

app/views/labos/index.html.erb
<h1>Labo's</h1>

<table>
  <tr>
    <th>Labo naam</th>
    <th>Studiepunten</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @labos.each do |labo| %>
  <tr>
    <td><%= labo.labo_naam %></td>
    <td><%= labo.studiepunten %></td>
    <td><%= link_to 'Show', labo %></td>
    <td><%= link_to 'Edit', edit_labo_path(labo) %></td>
    <td><%= link_to 'Destroy', labo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Labo', new_labo_path %>
<a href="http://localhost:3000/">Terug</a>

app/views/labos/new.html.erb
<h1>New labo</h1>

<%= render 'form' %>

<%= link_to 'Back', labos_path %>

app/views/labos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Labo naam:</b>
  <%= @labo.labo_naam %>
</p>

<p>
  <b>Studiepunten:</b>
  <%= @labo.studiepunten %>
</p>


<%= link_to 'Edit', edit_labo_path(@labo) %> |
<%= link_to 'Back', labos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EndApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lijst/index.html.erb
<h1>Lijsten</h1>

<a href="http://localhost:3000/">Terug</a>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Studenten</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.first_name %></td>
    <td><%= student.last_name %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>
<a href="http://localhost:3000/">Terug</a>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @student.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @student.last_name %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>